### ISSUE TITLE
Vignette Links are broken 

### ISSUE THREAD

**Issue by SawyerRSmith** [bailey-lab/coiaf#27]
### Maintenance Request

Vignette Links are broken.

#### Code Example

Ex: followed hyperlink to vignettes on website and GitHub. Both result in the following:
"The 'bailey-lab/coiaf' repository doesn't contain the 'analysis/vignettes/example_real_data.Rmd' path in 'main'. "

I thrive on pictures and guides, a vignette would be great! Thanks guys:)

**Comment by arisp99** [comment]
The vignette links on the site should now be fixed. Thanks for finding this!
